/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class ClinicHomePage extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClinicHomePage.class.getName());

	/**
	 * Creates new form ClinicHomePage
	 */
	public ClinicHomePage() {
		initComponents();
		greyBg.setBackground(new Color(153,153,153,150));
		BcshsSactxt.setBackground(new Color(153,153,153));
		panelMainBg.setBackground(new Color(204,204,204,100));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                ClinicSys = new javax.swing.JLabel();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jButton6 = new javax.swing.JButton();
                jButton7 = new javax.swing.JButton();
                greyBg = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                BcshsSactxt = new javax.swing.JLabel();
                panelMainBg = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));
                jPanel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                ClinicSys.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
                ClinicSys.setText("Clinic System");
                jPanel2.add(ClinicSys, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 410, -1));

                jButton3.setBackground(new java.awt.Color(115, 115, 115));
                jButton3.setForeground(new java.awt.Color(255, 255, 255));
                jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, 50));

                jButton4.setBackground(new java.awt.Color(115, 115, 115));
                jButton4.setForeground(new java.awt.Color(255, 255, 255));
                jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 120, 50));

                jButton5.setBackground(new java.awt.Color(115, 115, 115));
                jButton5.setForeground(new java.awt.Color(255, 255, 255));
                jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 120, 50));

                jButton6.setBackground(new java.awt.Color(115, 115, 115));
                jButton6.setForeground(new java.awt.Color(255, 255, 255));
                jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 120, 50));

                jButton7.setBackground(new java.awt.Color(115, 115, 115));
                jButton7.setForeground(new java.awt.Color(255, 255, 255));
                jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 120, 50));

                greyBg.setBackground(new java.awt.Color(153, 153, 153));
                greyBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/logo_school-removebg-preview.png"))); // NOI18N
                greyBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

                jPanel2.add(greyBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 100));

                jPanel1.setBackground(new java.awt.Color(102, 102, 102));

                BcshsSactxt.setBackground(new java.awt.Color(51, 51, 51));
                BcshsSactxt.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
                BcshsSactxt.setForeground(new java.awt.Color(255, 255, 255));
                BcshsSactxt.setText("Biñan City Señior Highschool - San Antonio Campus");
                BcshsSactxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                BcshsSactxt.setFocusable(false);
                BcshsSactxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                BcshsSactxt.setVerifyInputWhenFocusTarget(false);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(92, Short.MAX_VALUE)
                                .addComponent(BcshsSactxt, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(BcshsSactxt))
                );

                jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 670, 30));

                panelMainBg.setBackground(new java.awt.Color(204, 204, 204));

                javax.swing.GroupLayout panelMainBgLayout = new javax.swing.GroupLayout(panelMainBg);
                panelMainBg.setLayout(panelMainBgLayout);
                panelMainBgLayout.setHorizontalGroup(
                        panelMainBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 770, Short.MAX_VALUE)
                );
                panelMainBgLayout.setVerticalGroup(
                        panelMainBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 430, Short.MAX_VALUE)
                );

                jPanel2.add(panelMainBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 430));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/6226336049911680989.jpg"))); // NOI18N
                jLabel2.setText("jLabel2");
                jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 430));

                getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 771, 430));

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new ClinicHomePage().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel BcshsSactxt;
        private javax.swing.JLabel ClinicSys;
        private javax.swing.JPanel greyBg;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JButton jButton7;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel panelMainBg;
        // End of variables declaration//GEN-END:variables
}
