/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class ClinicSystemHome extends javax.swing.JFrame {

	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClinicSystemHome.class.getName());

	/**
	 * Creates new form ClinicHomePage
	 */
	public ClinicSystemHome() {
		initComponents();
		loadProfilePicture();
		greyBg.setBackground(new Color(153, 153, 153, 150));
		BcshsSactxt.setBackground(new Color(153, 153, 153));
		panelMainBg.setBackground(new Color(204, 204, 204, 100));

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                greyBg = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                Profile = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                BcshsSactxt = new javax.swing.JLabel();
                panelMainBg = new javax.swing.JPanel();
                consultationFrame = new javax.swing.JButton();
                ClinicSys = new javax.swing.JLabel();
                databaseStudentBtn = new javax.swing.JButton();
                databaseStudentRegistration = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));
                jPanel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                greyBg.setBackground(new java.awt.Color(153, 153, 153));
                greyBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/logo_school-removebg-preview.png"))); // NOI18N
                greyBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

                Profile.setText("Profile");
                Profile.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ProfileMouseClicked(evt);
                        }
                });
                greyBg.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

                jPanel2.add(greyBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 100));

                jPanel1.setBackground(new java.awt.Color(102, 102, 102));

                BcshsSactxt.setBackground(new java.awt.Color(51, 51, 51));
                BcshsSactxt.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
                BcshsSactxt.setForeground(new java.awt.Color(255, 255, 255));
                BcshsSactxt.setText("Biñan City Señior Highschool - San Antonio Campus");
                BcshsSactxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                BcshsSactxt.setFocusable(false);
                BcshsSactxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                BcshsSactxt.setVerifyInputWhenFocusTarget(false);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(92, Short.MAX_VALUE)
                                .addComponent(BcshsSactxt, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(BcshsSactxt))
                );

                jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 670, 30));

                panelMainBg.setBackground(new java.awt.Color(204, 204, 204));

                consultationFrame.setBackground(new java.awt.Color(115, 115, 115));
                consultationFrame.setForeground(new java.awt.Color(255, 255, 255));
                consultationFrame.setText("Consultation");
                consultationFrame.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                consultationFrameActionPerformed(evt);
                        }
                });

                ClinicSys.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
                ClinicSys.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                ClinicSys.setText("Clinic System");

                databaseStudentBtn.setBackground(new java.awt.Color(115, 115, 115));
                databaseStudentBtn.setForeground(new java.awt.Color(255, 255, 255));
                databaseStudentBtn.setText("Students Basic Information");
                databaseStudentBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                databaseStudentBtnActionPerformed(evt);
                        }
                });

                databaseStudentRegistration.setBackground(new java.awt.Color(115, 115, 115));
                databaseStudentRegistration.setForeground(new java.awt.Color(255, 255, 255));
                databaseStudentRegistration.setText("Register a Student");
                databaseStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                databaseStudentRegistrationActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout panelMainBgLayout = new javax.swing.GroupLayout(panelMainBg);
                panelMainBg.setLayout(panelMainBgLayout);
                panelMainBgLayout.setHorizontalGroup(
                        panelMainBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMainBgLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ClinicSys, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174))
                        .addGroup(panelMainBgLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(databaseStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(consultationFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(databaseStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(78, Short.MAX_VALUE))
                );
                panelMainBgLayout.setVerticalGroup(
                        panelMainBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainBgLayout.createSequentialGroup()
                                .addContainerGap(179, Short.MAX_VALUE)
                                .addComponent(ClinicSys)
                                .addGap(90, 90, 90)
                                .addGroup(panelMainBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(consultationFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(databaseStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(databaseStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83))
                );

                jPanel2.add(panelMainBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 460));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/6226336049911680989.jpg"))); // NOI18N
                jLabel2.setText("jLabel2");
                jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 430));

                getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 771, 430));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void databaseStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseStudentBtnActionPerformed
		// TODO add your handling code here:
		StudentData studentDatabase = new StudentData();
		studentDatabase.setVisible(true);
		this.dispose();


        }//GEN-LAST:event_databaseStudentBtnActionPerformed

        private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
		// TODO add your handling code here:
		
		Profile profile =new Profile();
		this.dispose();
		profile.setVisible(true);
		
        }//GEN-LAST:event_ProfileMouseClicked

        private void consultationFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationFrameActionPerformed
                // TODO add your handling code here:
		
		NurseConsultationFrame consultation = new NurseConsultationFrame();
		
		consultation.setVisible(true);
		
		this.dispose();
        }//GEN-LAST:event_consultationFrameActionPerformed

        private void databaseStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseStudentRegistrationActionPerformed
                // TODO add your handling code here:
		RegistrationStudent registration = new RegistrationStudent();
		
		registration.show(true);
		this.dispose();
		
        }//GEN-LAST:event_databaseStudentRegistrationActionPerformed
	private void loadProfilePicture() {
		// Smaller size for the header, e.g., 50x50
		javax.swing.ImageIcon icon = ProfileManager.getCircularProfilePicture(50, 50);
		if (icon != null) {
			Profile.setIcon(icon);
			Profile.setText("");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new ClinicSystemHome().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel BcshsSactxt;
        private javax.swing.JLabel ClinicSys;
        private javax.swing.JLabel Profile;
        private javax.swing.JButton consultationFrame;
        private javax.swing.JButton databaseStudentBtn;
        private javax.swing.JButton databaseStudentRegistration;
        private javax.swing.JPanel greyBg;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel panelMainBg;
        // End of variables declaration//GEN-END:variables

}
