/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class LogIn extends javax.swing.JFrame {
     Connection con;
   PreparedStatement pst;
   ResultSet rs;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogIn.class.getName());

    /**
     * Creates new form LogIn
     */
    public LogIn() throws ClassNotFoundException, SQLException {
        initComponents();
	violetBg.setBackground(new Color(38,26,114,150));
	UIManager.put("Button.arc", 999);
        Connect();
	
    }
 private void Connect() throws ClassNotFoundException, SQLException {
  Class.forName("com.mysql.jdbc.Driver");      
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin_data","root","");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                NameOfThePage = new javax.swing.JLabel();
                LogInNameLogo = new javax.swing.JLabel();
                LogInUserName = new javax.swing.JTextField();
                LogInBtn = new javax.swing.JButton();
                LogInPass = new javax.swing.JPasswordField();
                jLabel3 = new javax.swing.JLabel();
                violetBg = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/6226336049911681021.jpg"))); // NOI18N

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setAutoRequestFocus(false);
                setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
                setUndecorated(true);
                setResizable(false);
                addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                formFocusGained(evt);
                        }
                });

                jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
                jPanel1.setDoubleBuffered(false);
                jPanel1.setOpaque(false);
                jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                jPanel1MouseDragged(evt);
                        }
                });
                jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                jPanel1FocusGained(evt);
                        }
                });
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel3.setOpaque(false);

                NameOfThePage.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
                NameOfThePage.setText("System Clinic");

                LogInNameLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                LogInNameLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/logo_school-removebg-preview.png"))); // NOI18N

                LogInUserName.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
                LogInUserName.setForeground(new java.awt.Color(102, 102, 102));
                LogInUserName.setText("Enter Username");
                LogInUserName.setToolTipText("");
                LogInUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.white));
                LogInUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                LogInUserName.setOpaque(true);
                LogInUserName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                LogInUserNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                LogInUserNameFocusLost(evt);
                        }
                });
                LogInUserName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInUserNameActionPerformed(evt);
                        }
                });

                LogInBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                LogInBtn.setForeground(new java.awt.Color(38, 0, 114));
                LogInBtn.setText("Login");
                LogInBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInBtnActionPerformed(evt);
                        }
                });

                LogInPass.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
                LogInPass.setText("Enter Password");
                LogInPass.setActionCommand("<Not Set>");
                LogInPass.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                LogInPassFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                LogInPassFocusLost(evt);
                        }
                });
                LogInPass.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInPassActionPerformed(evt);
                        }
                });

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"))); // NOI18N

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(LogInNameLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(NameOfThePage))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LogInUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(LogInPass)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel3))))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addComponent(LogInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(LogInNameLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NameOfThePage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LogInUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(LogInPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel3)))
                                .addGap(32, 32, 32)
                                .addComponent(LogInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                );

                jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 330, 420));

                violetBg.setBackground(new java.awt.Color(38, 26, 114));

                javax.swing.GroupLayout violetBgLayout = new javax.swing.GroupLayout(violetBg);
                violetBg.setLayout(violetBgLayout);
                violetBgLayout.setHorizontalGroup(
                        violetBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 470, Short.MAX_VALUE)
                );
                violetBgLayout.setVerticalGroup(
                        violetBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 280, Short.MAX_VALUE)
                );

                jPanel1.add(violetBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 470, 280));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/6226336049911681021.jpg"))); // NOI18N
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 570));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
                // TODO add your handling code here:
		
        }//GEN-LAST:event_jPanel1FocusGained

        private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
                // TODO add your handling code here:
		
        }//GEN-LAST:event_jPanel1MouseDragged

        private void LogInPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInPassActionPerformed
                // TODO add your handling code here:

        }//GEN-LAST:event_LogInPassActionPerformed

        private void LogInPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LogInPassFocusLost
                // TODO add your handling code here:

                if(LogInPass.getText().equals("")){
                        LogInPass.setEchoChar((char) 0);
                        LogInPass.setText("Enter Password");
                        LogInPass.setForeground(new Color(153,153,153));
                }
        }//GEN-LAST:event_LogInPassFocusLost

        private void LogInPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LogInPassFocusGained
                // TODO add your handling code here:

                if(LogInPass.getText().equals("Enter Password")){
                        LogInPass.setEchoChar(('*')  );
                        LogInPass.setText("");
                        LogInPass.setForeground(new Color(0,0,0));

                }

        }//GEN-LAST:event_LogInPassFocusGained

        private void LogInUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInUserNameActionPerformed
                // TODO add your handling code here:

        }//GEN-LAST:event_LogInUserNameActionPerformed

        private void LogInUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LogInUserNameFocusLost
                // TODO add your handling code here:
                if(LogInUserName.getText().equals("")){
                        LogInUserName.setText("Enter Username");
                        LogInUserName.setForeground(new Color(153,153,153));
                }
        }//GEN-LAST:event_LogInUserNameFocusLost

        private void LogInUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LogInUserNameFocusGained
                // TODO add your handling code here:
                if(LogInUserName.getText().equals("Enter Username")){
                        LogInUserName.setText("");
                        LogInUserName.setForeground(new Color(153,153,153));
                }
        }//GEN-LAST:event_LogInUserNameFocusGained

        private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
                // TODO add your handling code here:
                String Username = LogInUserName.getText();
                String Password = LogInPass.getText();
		
		   try {
        //if me laman; else wala
        if (Username.isEmpty() || Password.isEmpty()){
             JOptionPane.showMessageDialog(this, "Fill the required field first!");
        }
        else {
    
        
        pst = con.prepareStatement("select * from adminregistration where binary UserName=? AND binary Password=?");
           pst.setString(1, Username);
           pst.setString(2, Password);
           rs = pst.executeQuery();
           if (rs.next())// checks if the us and pass are in the database//
           {
               JOptionPane.showMessageDialog(this, "Log in successful!");
	       	ClinicHomePage home = new ClinicHomePage();
					home.setVisible(true);
					this.dispose();
           }
    }
                } catch (SQLException ex) {
        Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
    }
        }//GEN-LAST:event_LogInBtnActionPerformed

        private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
                // TODO add your handling code here:
        }//GEN-LAST:event_formFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
		try {
			new LogIn().setVisible(true);
		} catch (ClassNotFoundException ex) {
			System.getLogger(LogIn.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
		} catch (SQLException ex) {
			System.getLogger(LogIn.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
		}
	});
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton LogInBtn;
        private javax.swing.JLabel LogInNameLogo;
        private javax.swing.JPasswordField LogInPass;
        private javax.swing.JTextField LogInUserName;
        private javax.swing.JLabel NameOfThePage;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JPanel violetBg;
        // End of variables declaration//GEN-END:variables

   
}
