/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class LogIn extends javax.swing.JFrame {

	Connection con;
	PreparedStatement pst;
	ResultSet rs;
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogIn.class.getName());

	/**
	 * Creates new form LogIn
	 */
	public LogIn() throws ClassNotFoundException, SQLException {
		initComponents();
		LogInPass.requestFocus();
		violetBg.setBackground(new Color(38, 26, 114, 150));
		UIManager.put("Button.arc", 999);

		Connect();

	}

	private void Connect() throws ClassNotFoundException, SQLException {
		con = DatabaseConnector.getAdminConnection();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jLabel3 = new javax.swing.JLabel();
                jButton1 = new ClinicSystem.RoundedButton();
                jLabel11 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                LogInNameLogo = new javax.swing.JLabel();
                LogInBtn = new ClinicSystem.RoundedButton();
                eyeClosedPass = new javax.swing.JLabel();
                LogInPass = new javax.swing.JPasswordField();
                NewUserBtn = new javax.swing.JButton();
                LogInUserName = new ClinicSystem.RoundedTextField();
                LogInUserName.setText("Enter Username");
                LogInUserName.setForeground(new java.awt.Color(153, 153, 153));
                LogInUserName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                LogInUserNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                LogInUserNameFocusLost(evt);
                        }
                });
                violetBg = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/6226336049911681021_1.jpg"))); // NOI18N

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"))); // NOI18N

                jButton1.setText("jButton1");

                jLabel11.setBackground(new java.awt.Color(51, 51, 255));
                jLabel11.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(38, 26, 114));
                jLabel11.setText("Clinic System");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("LogIn Page");
                setAutoRequestFocus(false);
                setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
                setResizable(false);

                jPanel1.setDoubleBuffered(false);
                jPanel1.setOpaque(false);
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel3.setOpaque(false);
                jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel12.setBackground(new java.awt.Color(51, 51, 255));
                jLabel12.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(255, 255, 255));
                jLabel12.setText("System Clinic");
                jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 230, -1));

                LogInNameLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                LogInNameLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/6226336049911681013-removebg-preview(1).png"))); // NOI18N
                jPanel3.add(LogInNameLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 180, 150));

                LogInBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                LogInBtn.setForeground(new java.awt.Color(38, 0, 114));
                LogInBtn.setText("Login");
                LogInBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInBtnActionPerformed(evt);
                        }
                });
                jPanel3.add(LogInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 140, 50));

                eyeClosedPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"))); // NOI18N
                eyeClosedPass.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                eyeClosedPassMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                eyeClosedPassMouseReleased(evt);
                        }
                });
                jPanel3.add(eyeClosedPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 30, 100));

                LogInPass.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
                LogInPass.setText("Enter Password");
                LogInPass.setActionCommand("<Not Set>");
                LogInPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                LogInPass.addContainerListener(new java.awt.event.ContainerAdapter() {
                        public void componentAdded(java.awt.event.ContainerEvent evt) {
                                LogInPassComponentAdded(evt);
                        }
                });
                LogInPass.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                LogInPassFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                LogInPassFocusLost(evt);
                        }
                });
                LogInPass.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInPassActionPerformed(evt);
                        }
                });
                jPanel3.add(LogInPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 180, 40));

                NewUserBtn.setBackground(new java.awt.Color(38, 26, 114));
                NewUserBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
                NewUserBtn.setForeground(new java.awt.Color(255, 255, 255));
                NewUserBtn.setText("New user? Register Here");
                NewUserBtn.setBorder(null);
                NewUserBtn.setBorderPainted(false);
                NewUserBtn.setContentAreaFilled(false);
                NewUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                NewUserBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                NewUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                NewUserBtnMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                NewUserBtnMouseExited(evt);
                        }
                });
                NewUserBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NewUserBtnActionPerformed(evt);
                        }
                });
                jPanel3.add(NewUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 180, 20));

                jPanel3.add(LogInUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 40));

                jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 330, 420));

                violetBg.setBackground(new java.awt.Color(38, 26, 114));

                javax.swing.GroupLayout violetBgLayout = new javax.swing.GroupLayout(violetBg);
                violetBg.setLayout(violetBgLayout);
                violetBgLayout.setHorizontalGroup(
                        violetBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 480, Short.MAX_VALUE)
                );
                violetBgLayout.setVerticalGroup(
                        violetBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 430, Short.MAX_VALUE)
                );

                jPanel1.add(violetBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 480, 430));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/Kagawaran_ng_Edukasyon_Logo-removebg-preview(1).png"))); // NOI18N
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 49, 60));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/6226336049911681021_1.jpg"))); // NOI18N
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-460, 0, 1010, 570));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void LogInPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInPassActionPerformed
		// TODO add your handling code here:

        }//GEN-LAST:event_LogInPassActionPerformed

        private void LogInPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LogInPassFocusLost
		// TODO add your handling code here:

		if (LogInPass.getText().equals("")) {
			LogInPass.setEchoChar((char) 0);
			LogInPass.setText("Enter Password");
			LogInPass.setForeground(new Color(153, 153, 153));
		}
        }//GEN-LAST:event_LogInPassFocusLost

        private void LogInPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LogInPassFocusGained
		// TODO add your handling code here:

		if (LogInPass.getText().equals("Enter Password")) {
			LogInPass.setEchoChar(('*'));
			LogInPass.setText("");
			LogInPass.setForeground(new Color(0, 0, 0));

		}

        }//GEN-LAST:event_LogInPassFocusGained

        private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
		// TODO add your handling code here:
		String Username = LogInUserName.getText();
		String Password = LogInPass.getText();

		try {
			//if walang lama; else meron
			if (Username.contains("Enter Username") || Password.contains("Enter Password")) {
				JOptionPane.showMessageDialog(this, "Fill the required field first!");

			} else  {

				pst = con.prepareStatement("select * from adminregistration where UserName=? AND  Password=?");
				pst.setString(1, Username);
				pst.setString(2, Password);
				rs = pst.executeQuery();
				if (rs.next())// checks if the us and pass are in the database//
				{
					JOptionPane.showMessageDialog(this, "Log in successful!");
					Profile profile = new Profile();
					ClinicSystemHome home = new ClinicSystemHome();
					home.setVisible(true);
					profile.setVisible(true);
					pst.close();
					this.dispose();
				} else {
					// Failed Login (No matching record found)
					JOptionPane.showMessageDialog(this, "Invalid Username or Password.", "Authentication Failed", JOptionPane.ERROR_MESSAGE);
					pst.close();
				}

			}
		} catch (SQLException ex) {
			Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
				JOptionPane.showMessageDialog(this, "Error", "Authentication Failed", JOptionPane.ERROR_MESSAGE);
		}
        }//GEN-LAST:event_LogInBtnActionPerformed

    private void eyeClosedPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClosedPassMousePressed
	    // TODO add your handling code here:
	    ImageIcon icon = new ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-visible-24.png"));
	    icon.getImage().flush();
	    eyeClosedPass.setIcon(icon);
	    LogInPass.setEchoChar((char) 0);
    }//GEN-LAST:event_eyeClosedPassMousePressed

    private void eyeClosedPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClosedPassMouseReleased
	    // TODO add your handling code here:
	    ImageIcon icon = new ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"));
	    icon.getImage().flush();
	    eyeClosedPass.setIcon(icon);
	    if (LogInPass.getText().equals("Enter Password")) {
		    LogInPass.setText("");
	    } else {
		    LogInPass.setEchoChar('*');
	    }
    }//GEN-LAST:event_eyeClosedPassMouseReleased

        private void LogInPassComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_LogInPassComponentAdded
		// TODO add your handling code here:
        }//GEN-LAST:event_LogInPassComponentAdded

        private void NewUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserBtnActionPerformed
		// TODO add your handling code here:

		RegistrationAdmin registerNewUser = new RegistrationAdmin();
		registerNewUser.setVisible(true);
		this.dispose();
        }//GEN-LAST:event_NewUserBtnActionPerformed

        private void NewUserBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserBtnMouseEntered
		// TODO add your handling code here:
		NewUserBtn.setForeground(new Color(0, 0, 0));

        }//GEN-LAST:event_NewUserBtnMouseEntered

        private void NewUserBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserBtnMouseExited
		// TODO add your handling code here:
		NewUserBtn.setForeground(new Color(255, 255, 255));
        }//GEN-LAST:event_NewUserBtnMouseExited

        private void LogInUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LogInUserNameFocusGained
                // TODO add your handling code here:
		if (LogInUserName.getText().equals("Enter Username")) {
                        LogInUserName.setText("");
                        LogInUserName.setForeground(new Color(0, 0, 0));
                }
        }//GEN-LAST:event_LogInUserNameFocusGained

        private void LogInUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LogInUserNameFocusLost
                // TODO add your handling code here:
		if (LogInUserName.getText().equals("")) {
                        LogInUserName.setText("Enter Username");
                        LogInUserName.setForeground(new Color(153, 153, 153));
                }
        }//GEN-LAST:event_LogInUserNameFocusLost

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		//LogInPass.requestFocus();
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		DatabaseInitializer.initializeDatabases();
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			try {
				new LogIn().setVisible(true);

			} catch (ClassNotFoundException ex) {
				System.getLogger(LogIn.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
			} catch (SQLException ex) {
				System.getLogger(LogIn.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private ClinicSystem.RoundedButton LogInBtn;
        private javax.swing.JLabel LogInNameLogo;
        private javax.swing.JPasswordField LogInPass;
        private javax.swing.JTextField LogInUserName;
        private javax.swing.JButton NewUserBtn;
        private javax.swing.JLabel eyeClosedPass;
        private ClinicSystem.RoundedButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JPanel violetBg;
        // End of variables declaration//GEN-END:variables

}
