/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author Admin
 */
public class NurseConsultationFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NurseConsultationFrame.class.getName());

    /**
     * Creates new form ConsultationGUI
     */
    public NurseConsultationFrame() {
        initComponents();
        refreshDiagnosticsTable("");
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosticsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblNotes = new javax.swing.JLabel();
        jButton1 = new ClinicSystem.RoundedButton();
        backToHome = new ClinicSystem.RoundedButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRefresh = new ClinicSystem.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(38, 26, 114));

        diagnosticsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        diagnosticsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diagnosticsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(diagnosticsTable);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        lblNotes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNotes.setForeground(new java.awt.Color(255, 255, 255));
        lblNotes.setText("Diagnostic Notes:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(38, 26, 114));
        jButton1.setText("Save Notes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backToHome.setBackground(new java.awt.Color(255, 255, 255));
        backToHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backToHome.setForeground(new java.awt.Color(38, 26, 114));
        backToHome.setText("Home");
        backToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 26, 114));
        jLabel2.setText("Nurse Consultation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search Student:");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNotes)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(backToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblNotes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(backToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Save and Update button handler
        int selectedRow = diagnosticsTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a student record from the table to update notes.",
                    "Selection Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the diagnostic_id from the selected row (first column)
        Object diagnosticIdObj = diagnosticsTable.getModel().getValueAt(selectedRow, 0);
        int diagnosticId = Integer.parseInt(diagnosticIdObj.toString());

        // Get the new notes from the text area
        String newNotes = jTextArea1.getText().trim();

        if (newNotes.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter diagnostic notes before saving.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Update the database
        String sql = "UPDATE diagnostics SET diagnostic_notes = ?, created_at = CURRENT_TIMESTAMP WHERE diagnostic_id = ?";

        try (Connection conn = DatabaseConnector.getStudentConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, newNotes);
            pstmt.setInt(2, diagnosticId);

            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                        "Diagnostic notes saved successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                // Clear the text area
                jTextArea1.setText("");

                // Refresh the table to show updated data
                refreshDiagnosticsTable(txtSearch.getText().trim());
            } else {
                JOptionPane.showMessageDialog(this,
                        "No records were updated. Please try again.",
                        "Update Failed",
                        JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Database Error: Could not save notes.\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "SQL Error saving notes", e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void diagnosticsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diagnosticsTableMouseClicked
        // When a row is clicked, load the current notes into the text area
        int selectedRow = diagnosticsTable.getSelectedRow();

        if (selectedRow != -1) {
            // Get the diagnostic notes from column 3 (adjust index if needed)
            Object notesObj = diagnosticsTable.getModel().getValueAt(selectedRow, 3);
            String currentNotes = (notesObj != null) ? notesObj.toString() : "";

            // Display in text area for editing
            jTextArea1.setText(currentNotes);
        }
    }//GEN-LAST:event_diagnosticsTableMouseClicked

    private void backToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeActionPerformed
        // TODO add your handling code here:
        ClinicSystemHome home = new ClinicSystemHome();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToHomeActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // Search as you type
        String query = txtSearch.getText().trim();
        refreshDiagnosticsTable(query);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        txtSearch.setText("");
        refreshDiagnosticsTable("");
        jTextArea1.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Initialize database
        DatabaseInitializer.initializeDatabases();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NurseConsultationFrame().setVisible(true));
    }

    /**
     * Refresh the diagnostics table from database
     */
    public void refreshDiagnosticsTable(String searchQuery) {
        // Select all necessary fields from the diagnostics table
        String sql = "SELECT diagnostic_id, created_at, student_name, diagnostic_notes, student_lrn_fk FROM diagnostics";
        
        if (searchQuery != null && !searchQuery.isEmpty()) {
            sql += " WHERE student_name LIKE ? OR student_lrn_fk LIKE ?";
        }
        
        sql += " ORDER BY created_at DESC";

        try (Connection conn = DatabaseConnector.getStudentConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            if (searchQuery != null && !searchQuery.isEmpty()) {
                String likeQuery = "%" + searchQuery + "%";
                pstmt.setString(1, likeQuery);
                pstmt.setString(2, likeQuery);
            }

            try (ResultSet rs = pstmt.executeQuery()) {
                // Use DbUtils to convert ResultSet to TableModel
                DefaultTableModel model = (DefaultTableModel) DbUtils.resultSetToTableModel(rs);
                diagnosticsTable.setModel(model);

                // Set column headers
                if (model.getColumnCount() > 0) {
                    diagnosticsTable.getColumnModel().getColumn(0).setHeaderValue("ID");
                    diagnosticsTable.getColumnModel().getColumn(1).setHeaderValue("Visit Date");
                    diagnosticsTable.getColumnModel().getColumn(2).setHeaderValue("Student Name");
                    diagnosticsTable.getColumnModel().getColumn(3).setHeaderValue("Diagnostic Notes");
                    diagnosticsTable.getColumnModel().getColumn(4).setHeaderValue("LRN");
                }
                
                // Hide ID column if desired, or keep it for reference
                // diagnosticsTable.removeColumn(diagnosticsTable.getColumnModel().getColumn(0));

                System.out.println("✓ Diagnostics table refreshed: " + model.getRowCount() + " records");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Database Error: Cannot refresh table.\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "SQL Error refreshing table", e);
        }
    }

    /**
     * Create initial diagnostic record for a newly registered student
     * This is called from RegistrationStudent after successful registration
     */
    public void createInitialDiagnosticRecord(String lrn, String firstName, String lastName) {
        String fullName = firstName + " " + lastName;
        String sql = "INSERT INTO diagnostics (student_lrn_fk, student_name, diagnostic_notes) VALUES (?, ?, ?)";

        try (Connection conn = DatabaseConnector.getStudentConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, lrn);
            pstmt.setString(2, fullName);
            pstmt.setString(3, "Student registered on " + new java.util.Date().toString() + ". Awaiting clinic visit.");

            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("✓ Initial diagnostic record created for: " + fullName);
            }

            // Refresh the nurse's GUI immediately after a new record is created
            refreshDiagnosticsTable("");

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "SQL Error creating initial record", e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ClinicSystem.RoundedButton backToHome;
    private ClinicSystem.RoundedButton btnRefresh;
    private javax.swing.JTable diagnosticsTable;
    private ClinicSystem.RoundedButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}