/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class NurseConsultationFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NurseConsultationFrame.class.getName());

    /**
     * Creates new form ConsultationGUI
     */
    public NurseConsultationFrame() {
        initComponents();
        refreshDiagnosticsTable();
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                diagnosticsTable = new javax.swing.JTable();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                diagnosticsTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(diagnosticsTable);

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane2.setViewportView(jTextArea1);

                jButton1.setText("Save and Update");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(jButton1)))
                                .addGap(279, 279, 279))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Save and Update button handler
        int selectedRow = diagnosticsTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a student record from the table to update notes.",
                    "Selection Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the diagnostic_id from the selected row (first column)
        Object diagnosticIdObj = diagnosticsTable.getModel().getValueAt(selectedRow, 0);
        int diagnosticId = Integer.parseInt(diagnosticIdObj.toString());

        // Get the new notes from the text area
        String newNotes = jTextArea1.getText().trim();

        if (newNotes.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter diagnostic notes before saving.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Update the database
        String sql = "UPDATE diagnostics SET diagnostic_notes = ?, created_at = CURRENT_TIMESTAMP WHERE diagnostic_id = ?";

        try (Connection conn = DatabaseConnector.getStudentConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, newNotes);
            pstmt.setInt(2, diagnosticId);

            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                        "Diagnostic notes saved successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                // Clear the text area
                jTextArea1.setText("");

                // Refresh the table to show updated data
                refreshDiagnosticsTable();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No records were updated. Please try again.",
                        "Update Failed",
                        JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Database Error: Could not save notes.\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "SQL Error saving notes", e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void diagnosticsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diagnosticsTableMouseClicked
        // When a row is clicked, load the current notes into the text area
        int selectedRow = diagnosticsTable.getSelectedRow();

        if (selectedRow != -1) {
            // Get the diagnostic notes from column 3 (adjust index if needed)
            Object notesObj = diagnosticsTable.getModel().getValueAt(selectedRow, 3);
            String currentNotes = (notesObj != null) ? notesObj.toString() : "";

            // Display in text area for editing
            jTextArea1.setText(currentNotes);
        }
    }//GEN-LAST:event_diagnosticsTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Initialize database
        DatabaseInitializer.initializeDatabases();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NurseConsultationFrame().setVisible(true));
    }

    /**
     * Refresh the diagnostics table from database
     */
    public void refreshDiagnosticsTable() {
        // Select all necessary fields from the diagnostics table
        String sql = "SELECT diagnostic_id, created_at, student_name, diagnostic_notes, student_lrn_fk FROM diagnostics ORDER BY created_at DESC";

        try (Connection conn = DatabaseConnector.getStudentConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            // Use DbUtils to convert ResultSet to TableModel
            DefaultTableModel model = (DefaultTableModel) DbUtils.resultSetToTableModel(rs);
            diagnosticsTable.setModel(model);

            // Set column headers
            if (model.getColumnCount() > 0) {
                diagnosticsTable.getColumnModel().getColumn(0).setHeaderValue("ID");
                diagnosticsTable.getColumnModel().getColumn(1).setHeaderValue("Visit Date");
                diagnosticsTable.getColumnModel().getColumn(2).setHeaderValue("Student Name");
                diagnosticsTable.getColumnModel().getColumn(3).setHeaderValue("Diagnostic Notes");
                diagnosticsTable.getColumnModel().getColumn(4).setHeaderValue("LRN");
            }

            System.out.println("✓ Diagnostics table refreshed: " + model.getRowCount() + " records");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Database Error: Cannot refresh table.\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "SQL Error refreshing table", e);
        }
    }

    /**
     * Create initial diagnostic record for a newly registered student
     * This is called from RegistrationStudent after successful registration
     */
    public void createInitialDiagnosticRecord(String lrn, String firstName, String lastName) {
        String fullName = firstName + " " + lastName;
        String sql = "INSERT INTO diagnostics (student_lrn_fk, student_name, diagnostic_notes) VALUES (?, ?, ?)";

        try (Connection conn = DatabaseConnector.getStudentConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, lrn);
            pstmt.setString(2, fullName);
            pstmt.setString(3, "Student registered on " + new java.util.Date().toString() + ". Awaiting clinic visit.");

            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("✓ Initial diagnostic record created for: " + fullName);
            }

            // Refresh the nurse's GUI immediately after a new record is created
            refreshDiagnosticsTable();

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "SQL Error creating initial record", e);
        }
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTable diagnosticsTable;
        private javax.swing.JButton jButton1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea1;
        // End of variables declaration//GEN-END:variables
}