/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

/**
 *
 * @author Admin
 */
public class Profile extends javax.swing.JFrame {

	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());

	/**
	 * Creates new form Profile
	 */
	public Profile() {
		initComponents();
		loadProfilePicture();
	}

	private void loadProfilePicture() {
		// 150, 150 is the width and height. Adjust if your label is different size.
		javax.swing.ImageIcon icon = ProfileManager.getScaledProfilePicture(150, 150);
		if (icon != null) {
			profileLabel.setIcon(icon);
			profileLabel.setText("");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jFrame1 = new javax.swing.JFrame();
                jFrame2 = new javax.swing.JFrame();
                jFrame3 = new javax.swing.JFrame();
                jFrame4 = new javax.swing.JFrame();
                jFrame5 = new javax.swing.JFrame();
                jDialog1 = new javax.swing.JDialog();
                jFrame6 = new javax.swing.JFrame();
                jFrame7 = new javax.swing.JFrame();
                jFrame8 = new javax.swing.JFrame();
                jMenu1 = new javax.swing.JMenu();
                jMenu2 = new javax.swing.JMenu();
                jFileChooser1 = new javax.swing.JFileChooser();
                jPanel1 = new javax.swing.JPanel();
                profileLabel = new javax.swing.JLabel();
                uploadBtn = new javax.swing.JButton();

                javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
                jFrame1.getContentPane().setLayout(jFrame1Layout);
                jFrame1Layout.setHorizontalGroup(
                        jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jFrame1Layout.setVerticalGroup(
                        jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
                jFrame2.getContentPane().setLayout(jFrame2Layout);
                jFrame2Layout.setHorizontalGroup(
                        jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jFrame2Layout.setVerticalGroup(
                        jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
                jFrame3.getContentPane().setLayout(jFrame3Layout);
                jFrame3Layout.setHorizontalGroup(
                        jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jFrame3Layout.setVerticalGroup(
                        jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
                jFrame4.getContentPane().setLayout(jFrame4Layout);
                jFrame4Layout.setHorizontalGroup(
                        jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jFrame4Layout.setVerticalGroup(
                        jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
                jFrame5.getContentPane().setLayout(jFrame5Layout);
                jFrame5Layout.setHorizontalGroup(
                        jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jFrame5Layout.setVerticalGroup(
                        jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
                jDialog1.getContentPane().setLayout(jDialog1Layout);
                jDialog1Layout.setHorizontalGroup(
                        jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jDialog1Layout.setVerticalGroup(
                        jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jFrame6Layout = new javax.swing.GroupLayout(jFrame6.getContentPane());
                jFrame6.getContentPane().setLayout(jFrame6Layout);
                jFrame6Layout.setHorizontalGroup(
                        jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jFrame6Layout.setVerticalGroup(
                        jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jFrame7Layout = new javax.swing.GroupLayout(jFrame7.getContentPane());
                jFrame7.getContentPane().setLayout(jFrame7Layout);
                jFrame7Layout.setHorizontalGroup(
                        jFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jFrame7Layout.setVerticalGroup(
                        jFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jFrame8Layout = new javax.swing.GroupLayout(jFrame8.getContentPane());
                jFrame8.getContentPane().setLayout(jFrame8Layout);
                jFrame8Layout.setHorizontalGroup(
                        jFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jFrame8Layout.setVerticalGroup(
                        jFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                jMenu1.setText("jMenu1");

                jMenu2.setText("jMenu2");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                profileLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                uploadBtn.setText("Upload Picture");
                uploadBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                uploadBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(146, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(131, 131, 131))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(uploadBtn)
                                                .addGap(149, 149, 149))))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(uploadBtn)
                                .addContainerGap(119, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
		// TODO add your handling code here:
		javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
		fileChooser.setDialogTitle("Select Profile Picture");
		fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "gif", "jpeg"));

		int userSelection = fileChooser.showOpenDialog(this);

		if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
			java.io.File fileToSave = fileChooser.getSelectedFile();
			boolean success = ProfileManager.saveProfilePicture(fileToSave);

			if (success) {
				javax.swing.JOptionPane.showMessageDialog(this, "Profile picture updated successfully!");
				loadProfilePicture(); // We will create this method next
			} else {
				javax.swing.JOptionPane.showMessageDialog(this, "Failed to save profile picture.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			}
		}


        }//GEN-LAST:event_uploadBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new Profile().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JDialog jDialog1;
        private javax.swing.JFileChooser jFileChooser1;
        private javax.swing.JFrame jFrame1;
        private javax.swing.JFrame jFrame2;
        private javax.swing.JFrame jFrame3;
        private javax.swing.JFrame jFrame4;
        private javax.swing.JFrame jFrame5;
        private javax.swing.JFrame jFrame6;
        private javax.swing.JFrame jFrame7;
        private javax.swing.JFrame jFrame8;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel profileLabel;
        private javax.swing.JButton uploadBtn;
        // End of variables declaration//GEN-END:variables
}
