/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class RegistrationAdmin extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationAdmin.class.getName());

    /**
     * Creates new form RegistrationAdmin
     */
    public RegistrationAdmin() {
        initComponents();
        Connect();
	violetBg.setBackground(new Color(38,26,114,150));
    }

    public final void Connect() {
        try {
            con = DatabaseConnector.getAdminConnection();
        } catch (SQLException ex) {
            System.getLogger(RegistrationAdmin.class.getName()).log(System.Logger.Level.ERROR,
                    (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel3 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                violetBg = new javax.swing.JPanel();
                employmentId = new ClinicSystem.RoundedTextField();
                eyeClosedConPass = new javax.swing.JLabel();
                eyeClosedPass = new javax.swing.JLabel();
                confirmPass = new javax.swing.JPasswordField();
                regPass = new javax.swing.JPasswordField();
                department = new ClinicSystem.RoundedTextField();
                regUserName = new ClinicSystem.RoundedTextField();
                regFirstName = new ClinicSystem.RoundedTextField();
                regLastName = new ClinicSystem.RoundedTextField();
                register = new javax.swing.JButton();
                alreadyRegisteredBtn = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                jPanel1.setForeground(new java.awt.Color(102, 102, 102));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                violetBg.setBackground(new java.awt.Color(38, 26, 114));
                violetBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                employmentId.setForeground(new java.awt.Color(153, 153, 153));
                employmentId.setText("Employment ID");
                employmentId.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                employmentIdFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                employmentIdFocusLost(evt);
                        }
                });
                employmentId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                employmentIdActionPerformed(evt);
                        }
                });
                violetBg.add(employmentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, 40));

                eyeClosedConPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"))); // NOI18N
                eyeClosedConPass.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                eyeClosedConPassMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                eyeClosedConPassMouseReleased(evt);
                        }
                });
                violetBg.add(eyeClosedConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

                eyeClosedPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"))); // NOI18N
                eyeClosedPass.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                eyeClosedPassMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                eyeClosedPassMouseReleased(evt);
                        }
                });
                violetBg.add(eyeClosedPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

                confirmPass.setText("Confirm Password");
                confirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                confirmPassFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                confirmPassFocusLost(evt);
                        }
                });
                violetBg.add(confirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 180, 40));

                regPass.setText("Password");
                regPass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                regPassMouseDragged(evt);
                        }
                });
                regPass.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regPassFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regPassFocusLost(evt);
                        }
                });
                violetBg.add(regPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 180, 40));

                department.setForeground(new java.awt.Color(153, 153, 153));
                department.setText("Department");
                department.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                departmentFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                departmentFocusLost(evt);
                        }
                });
                department.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                departmentActionPerformed(evt);
                        }
                });
                violetBg.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 180, 40));

                regUserName.setForeground(new java.awt.Color(153, 153, 153));
                regUserName.setText("Username");
                regUserName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regUserNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regUserNameFocusLost(evt);
                        }
                });
                violetBg.add(regUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 40));

                regFirstName.setForeground(new java.awt.Color(153, 153, 153));
                regFirstName.setText("FirstName");
                regFirstName.setMinimumSize(new java.awt.Dimension(80, 22));
                regFirstName.setPreferredSize(new java.awt.Dimension(80, 22));
                regFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regFirstNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regFirstNameFocusLost(evt);
                        }
                });
                regFirstName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regFirstNameActionPerformed(evt);
                        }
                });
                violetBg.add(regFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 80, 40));

                regLastName.setForeground(new java.awt.Color(153, 153, 153));
                regLastName.setText("LastName");
                regLastName.setMinimumSize(new java.awt.Dimension(80, 22));
                regLastName.setPreferredSize(new java.awt.Dimension(80, 22));
                regLastName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regLastNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regLastNameFocusLost(evt);
                        }
                });
                regLastName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regLastNameActionPerformed(evt);
                        }
                });
                violetBg.add(regLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 40));

                register.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
                register.setForeground(new java.awt.Color(38, 26, 114));
                register.setText("Register");
                register.setBorder(null);
                register.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                registerActionPerformed(evt);
                        }
                });
                violetBg.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 110, 40));

                alreadyRegisteredBtn.setBackground(new java.awt.Color(38, 26, 114));
                alreadyRegisteredBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
                alreadyRegisteredBtn.setForeground(new java.awt.Color(255, 255, 255));
                alreadyRegisteredBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                alreadyRegisteredBtn.setText("Already registered? LogIn");
                alreadyRegisteredBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                alreadyRegisteredBtn.setOpaque(true);
                alreadyRegisteredBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                alreadyRegisteredBtnMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                alreadyRegisteredBtnMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                alreadyRegisteredBtnMouseExited(evt);
                        }
                });
                violetBg.add(alreadyRegisteredBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 180, -1));

                jLabel5.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Register");
                violetBg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

                jLabel4.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Register");
                violetBg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

                jPanel1.add(violetBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 470));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/6226336049911681013-removebg-preview.png"))); // NOI18N
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 250, 480));

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/6226336049911680989_1.jpg"))); // NOI18N
                jLabel3.setText("jLabel3");
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 330, 480));

                jLabel1.setBackground(new java.awt.Color(51, 51, 255));
                jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(38, 26, 114));
                jLabel1.setText("Clinic System");
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void regLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLastNameActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_regLastNameActionPerformed

        private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_departmentActionPerformed

        private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
            // TODO add your handling code here:
            String EmploymentID = employmentId.getText();
            String firstName = regFirstName.getText();
            String lastName = regLastName.getText();
            String userName = regUserName.getText();
            String depart = department.getText();
            String password = regPass.getText();
            String conPass = confirmPass.getText();

            try {
                if (firstName.isEmpty()
                        || lastName.isEmpty()
                        || userName.isEmpty()
                        || depart.isEmpty()
                        || password.isEmpty()
                        || conPass.isEmpty()
                        && firstName.equals("FirstName")
                        || lastName.equals("LastName")
                        || userName.equals("Username")
                        || depart.equals("Department")
                        || password.equals("Password")
                        || conPass.equals("Confirm Password")) {
                    JOptionPane.showMessageDialog(this, "Please Fill all the needed Info", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (!password.equals(conPass)) {
                        JOptionPane.showMessageDialog(this, "Password don't Match");

                    } else {
                        String checkQuery = "SELECT COUNT(*) FROM adminregistration WHERE UserName = ?";
                        int count;
                        try (PreparedStatement checkSt = con.prepareStatement(checkQuery)) {
                            checkSt.setString(1, regUserName.getText()); // Get the text from the username field
                            try (ResultSet rs = checkSt.executeQuery()) {
                                count = 0;
                                if (rs.next()) {
                                    count = rs.getInt(1);
                                }
                            }
                        } // Get the text from the username field // Get the text from the username field

                        if (count > 0) {
                            // Username is already in the database
                            JOptionPane.showMessageDialog(null, "Username is already taken!", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {

                            pst = con.prepareStatement("insert into adminregistration(EmploymentId,FirstName,LastName,UserName,Department,Password,Confirm_Pass )"
                                    + "values(?,?,?,?,?,?,?)");
                            pst.setString(1, EmploymentID);
                            pst.setString(2, firstName);
                            pst.setString(3, lastName);
                            pst.setString(4, userName);
                            pst.setString(5, depart);
                            pst.setString(6, password);
                            pst.setString(7, conPass);
                            int result = pst.executeUpdate();

                            if (result == 1) {
                                JOptionPane.showMessageDialog(this, "Registration Succesfull");
                                employmentId.setText("");
                                regFirstName.setText("");
                                regLastName.setText("");
                                regUserName.setText("");
                                department.setText("");
                                regPass.setText("");
                                confirmPass.setText("");
                                LogIn loginPage = new LogIn();
                                loginPage.setVisible(true);
                                this.dispose();

                                pst.close();

                            }
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(RegistrationAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                System.getLogger(RegistrationAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        }//GEN-LAST:event_registerActionPerformed

        private void regFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusGained
            // TODO add your handling code here:
            if (regFirstName.getText().equals("FirstName")) {
                regFirstName.setText("");
                regFirstName.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_regFirstNameFocusGained

        private void regFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusLost
            // TODO add your handling code here:

            if (regFirstName.getText().equals("")) {
                regFirstName.setText("FirstName");

                regFirstName.setForeground(new Color(153, 153, 153));
            } else {
                regFirstName.setForeground(new Color(0, 0, 0));
            }


        }//GEN-LAST:event_regFirstNameFocusLost

        private void regLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusGained
            // TODO add your handling code here:
            if (regLastName.getText().equals("LastName")) {
                regLastName.setText("");
                regLastName.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_regLastNameFocusGained

        private void regLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusLost
            // TODO add your handling code here:
            if (regLastName.getText().equals("")) {
                regLastName.setText("LastName");
                regLastName.setForeground(new Color(153, 153, 153));
            } else {
                regLastName.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_regLastNameFocusLost

        private void regUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regUserNameFocusGained
            // TODO add your handling code here:
            if (regUserName.getText().equals("Username")) {
                regUserName.setText("");
                regUserName.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_regUserNameFocusGained

        private void regUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regUserNameFocusLost
            // TODO add your handling code here:
            if (regUserName.getText().equals("")) {
                regUserName.setText("Username");
                regUserName.setForeground(new Color(153, 153, 153));
            } else {
                regUserName.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_regUserNameFocusLost

        private void departmentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_departmentFocusGained
            // TODO add your handling code here:
            if (department.getText().equals("Department")) {
                department.setText("");
                department.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_departmentFocusGained

        private void departmentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_departmentFocusLost
            // TODO add your handling code here:
            if (department.getText().equals("")) {
                department.setText("Department");
                department.setForeground(new Color(153, 153, 153));
            } else {
                department.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_departmentFocusLost

        private void regFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFirstNameActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_regFirstNameActionPerformed

        private void regPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPassFocusGained
            // TODO add your handling code here:

            if (regPass.getText().equals("Password")) {
                regPass.setEchoChar('*');
                regPass.setText("");
                regPass.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_regPassFocusGained

        private void regPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPassFocusLost
            // TODO add your handling code here:

            if (regPass.getText().equals("")) {
                regPass.setEchoChar((char) 0);
                regPass.setText("Password");
                regPass.setForeground(new Color(153, 153, 153));
            } else {
                regPass.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_regPassFocusLost

        private void regPassMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regPassMouseDragged

        }//GEN-LAST:event_regPassMouseDragged

        private void confirmPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFocusGained
            // TODO add your handling code here:

            if (confirmPass.getText().equals("Confirm Password")) {
                confirmPass.setEchoChar('*');
                confirmPass.setText("");
                confirmPass.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_confirmPassFocusGained

        private void confirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFocusLost
            // TODO add your handling code here:

            if (confirmPass.getText().equals("")) {
                confirmPass.setEchoChar((char) 0);
                confirmPass.setText("Confirm Password");
                confirmPass.setForeground(new Color(153, 153, 153));
            } else {
                confirmPass.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_confirmPassFocusLost

        private void employmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employmentIdActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_employmentIdActionPerformed

        private void employmentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employmentIdFocusGained
            // TODO add your handling code here:
            if (employmentId.getText().equals("Employment ID")) {
                employmentId.setText("");
                employmentId.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_employmentIdFocusGained

        private void employmentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employmentIdFocusLost
            // TODO add your handling code here:
            if (employmentId.getText().equals("")) {
                employmentId.setText("Employment ID");
                employmentId.setForeground(new Color(153, 153, 153));
            } else {
                employmentId.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_employmentIdFocusLost

        private void eyeClosedPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClosedPassMousePressed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-visible-24.png"));
        icon.getImage().flush();
        eyeClosedPass.setIcon(icon);
        regPass.setEchoChar((char) 0);
    }//GEN-LAST:event_eyeClosedPassMousePressed

    private void eyeClosedPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClosedPassMouseReleased
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"));
        icon.getImage().flush();
        eyeClosedPass.setIcon(icon);
        regPass.setEchoChar('*');
    }//GEN-LAST:event_eyeClosedPassMouseReleased

    private void eyeClosedConPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClosedConPassMousePressed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-visible-24.png"));
        icon.getImage().flush();
        eyeClosedConPass.setIcon(icon);
        confirmPass.setEchoChar((char) 0);
    }//GEN-LAST:event_eyeClosedConPassMousePressed

    private void eyeClosedConPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClosedConPassMouseReleased
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"));
        icon.getImage().flush();
        eyeClosedConPass.setIcon(icon);
        confirmPass.setEchoChar('*');
    }//GEN-LAST:event_eyeClosedConPassMouseReleased

        private void alreadyRegisteredBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyRegisteredBtnMouseEntered
                // TODO add your handling code here:
		 alreadyRegisteredBtn.setForeground(Color.black);
        }//GEN-LAST:event_alreadyRegisteredBtnMouseEntered

        private void alreadyRegisteredBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyRegisteredBtnMouseExited
                // TODO add your handling code here:
		alreadyRegisteredBtn.setForeground(Color.white);
        }//GEN-LAST:event_alreadyRegisteredBtnMouseExited

        private void alreadyRegisteredBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyRegisteredBtnMouseClicked
                // TODO add your handling code here:
		LogIn alreadyRegistered = null;
	    try {
		    alreadyRegistered = new LogIn();
	    } catch (ClassNotFoundException ex) {
		    System.getLogger(RegistrationAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
	    } catch (SQLException ex) {
		    System.getLogger(RegistrationAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
	    }
		alreadyRegistered.setVisible(true);
		this.dispose();
        }//GEN-LAST:event_alreadyRegisteredBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationAdmin().setVisible(true));
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel alreadyRegisteredBtn;
        private javax.swing.JPasswordField confirmPass;
        private ClinicSystem.RoundedTextField department;
        private ClinicSystem.RoundedTextField employmentId;
        private javax.swing.JLabel eyeClosedConPass;
        private javax.swing.JLabel eyeClosedPass;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private ClinicSystem.RoundedTextField regFirstName;
        private ClinicSystem.RoundedTextField regLastName;
        private javax.swing.JPasswordField regPass;
        private ClinicSystem.RoundedTextField regUserName;
        private javax.swing.JButton register;
        private javax.swing.JPanel violetBg;
        // End of variables declaration//GEN-END:variables
}
