/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class RegistrationStudent extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationStudent.class.getName());

    /**
     * Creates new form RegistrationAdmin
     */
    public RegistrationStudent() {
        initComponents();
        Connect();
	 jPanel2.setBackground(new Color(38,26,114,200));
    }

    public final void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/admin_data", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            System.getLogger(RegistrationStudent.class.getName()).log(System.Logger.Level.ERROR,
                    (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                employmentId = new javax.swing.JTextField();
                Weight = new javax.swing.JTextField();
                regLastName = new javax.swing.JTextField();
                Sex = new javax.swing.JTextField();
                regFirstName = new javax.swing.JTextField();
                register = new javax.swing.JButton();
                Age = new javax.swing.JTextField();
                Height = new javax.swing.JTextField();
                Height1 = new javax.swing.JTextField();
                Height2 = new javax.swing.JTextField();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                pictureBg = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                jPanel1.setForeground(new java.awt.Color(102, 102, 102));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel2.setBackground(new java.awt.Color(38, 26, 114));
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Registration");
                jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

                employmentId.setForeground(new java.awt.Color(153, 153, 153));
                employmentId.setText("LRN");
                employmentId.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                employmentIdFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                employmentIdFocusLost(evt);
                        }
                });
                employmentId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                employmentIdActionPerformed(evt);
                        }
                });
                jPanel2.add(employmentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 178, 40));

                Weight.setForeground(new java.awt.Color(153, 153, 153));
                Weight.setText("Weight");
                Weight.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                WeightFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                WeightFocusLost(evt);
                        }
                });
                Weight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                WeightActionPerformed(evt);
                        }
                });
                jPanel2.add(Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 60, 40));

                regLastName.setForeground(new java.awt.Color(153, 153, 153));
                regLastName.setText("LastName");
                regLastName.setMinimumSize(new java.awt.Dimension(80, 22));
                regLastName.setPreferredSize(new java.awt.Dimension(80, 22));
                regLastName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regLastNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regLastNameFocusLost(evt);
                        }
                });
                regLastName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regLastNameActionPerformed(evt);
                        }
                });
                jPanel2.add(regLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, 40));

                Sex.setForeground(new java.awt.Color(153, 153, 153));
                Sex.setText("Sex");
                Sex.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                SexFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                SexFocusLost(evt);
                        }
                });
                jPanel2.add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 50, 40));

                regFirstName.setForeground(new java.awt.Color(153, 153, 153));
                regFirstName.setText("FirstName");
                regFirstName.setMinimumSize(new java.awt.Dimension(80, 22));
                regFirstName.setPreferredSize(new java.awt.Dimension(80, 22));
                regFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regFirstNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regFirstNameFocusLost(evt);
                        }
                });
                regFirstName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regFirstNameActionPerformed(evt);
                        }
                });
                jPanel2.add(regFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 40));

                register.setForeground(new java.awt.Color(38, 26, 114));
                register.setText("Register");
                register.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                registerActionPerformed(evt);
                        }
                });
                jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

                Age.setForeground(new java.awt.Color(153, 153, 153));
                Age.setText("Age");
                Age.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                AgeFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                AgeFocusLost(evt);
                        }
                });
                Age.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AgeActionPerformed(evt);
                        }
                });
                jPanel2.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 50, 40));

                Height.setForeground(new java.awt.Color(153, 153, 153));
                Height.setText("Height");
                Height.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                HeightFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                HeightFocusLost(evt);
                        }
                });
                Height.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HeightActionPerformed(evt);
                        }
                });
                jPanel2.add(Height, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 180, 40));

                Height1.setForeground(new java.awt.Color(153, 153, 153));
                Height1.setText("Height");
                Height1.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                Height1FocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                Height1FocusLost(evt);
                        }
                });
                Height1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Height1ActionPerformed(evt);
                        }
                });
                jPanel2.add(Height1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 180, 40));

                Height2.setForeground(new java.awt.Color(153, 153, 153));
                Height2.setText("Height");
                Height2.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                Height2FocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                Height2FocusLost(evt);
                        }
                });
                Height2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Height2ActionPerformed(evt);
                        }
                });
                jPanel2.add(Height2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, 40));

                jPanel3.setBackground(new java.awt.Color(38, 26, 114));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/logo_school-removebg-preview.png"))); // NOI18N

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(8, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addContainerGap(379, Short.MAX_VALUE))
                );

                jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, 480));

                jLabel3.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Student's");
                jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 340, 480));

                pictureBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/6226336049911680989.jpg"))); // NOI18N
                jPanel1.add(pictureBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 480));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, Short.MAX_VALUE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void regLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLastNameActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_regLastNameActionPerformed

        private void WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_WeightActionPerformed

        private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
            // TODO add your handling code here:
            String EmploymentID = employmentId.getText();
            String firstName = regFirstName.getText();
            String lastName = regLastName.getText();
            String userName = Sex.getText();
            String depart = Weight.getText();
            String password = regPass.getText();
            String conPass = confirmPass.getText();

            try {
                if (firstName.isEmpty()
                        || lastName.isEmpty()
                        || userName.isEmpty()
                        || depart.isEmpty()
                        || password.isEmpty()
                        || conPass.isEmpty()
                        && firstName.equals("FirstName")
                        || lastName.equals("LastName")
                        || userName.equals("Username")
                        || depart.equals("Department")
                        || password.equals("Password")
                        || conPass.equals("Confirm Password")) {
                    JOptionPane.showMessageDialog(this, "Please Fill all the needed Info", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (!password.equals(conPass)) {
                        JOptionPane.showMessageDialog(this, "Password don't Match");

                    } else {
                        String checkQuery = "SELECT COUNT(*) FROM adminregistration WHERE UserName = ?";
                        int count;
                        try (PreparedStatement checkSt = con.prepareStatement(checkQuery)) {
                            checkSt.setString(1, Sex.getText()); // Get the text from the username field
                            try (ResultSet rs = checkSt.executeQuery()) {
                                count = 0;
                                if (rs.next()) {
                                    count = rs.getInt(1);
                                }
                            }
                        } // Get the text from the username field // Get the text from the username field

                        if (count > 0) {
                            // Username is already in the database
                            JOptionPane.showMessageDialog(null, "Username is already taken!", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {

                            pst = con.prepareStatement("insert into adminregistration(EmploymentId,FirstName,LastName,UserName,Department,Password,Confirm_Pass )"
                                    + "values(?,?,?,?,?,?,?)");
                            pst.setString(1, EmploymentID);
                            pst.setString(2, firstName);
                            pst.setString(3, lastName);
                            pst.setString(4, userName);
                            pst.setString(5, depart);
                            pst.setString(6, password);
                            pst.setString(7, conPass);
                            int result = pst.executeUpdate();

                            if (result == 1) {
                                JOptionPane.showMessageDialog(this, "Registration Succesfull");
                                employmentId.setText("");
                                regFirstName.setText("");
                                regLastName.setText("");
                                Sex.setText("");
                                Weight.setText("");
                                regPass.setText("");
                                confirmPass.setText("");
                                LogIn loginPage = new LogIn();
                                loginPage.setVisible(true);
                                this.dispose();

                                pst.close();

                            }
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(RegistrationStudent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                System.getLogger(RegistrationStudent.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        }//GEN-LAST:event_registerActionPerformed

        private void regFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusGained
            // TODO add your handling code here:
            if (regFirstName.getText().equals("FirstName")) {
                regFirstName.setText("");
                regFirstName.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_regFirstNameFocusGained

        private void regFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusLost
            // TODO add your handling code here:

            if (regFirstName.getText().equals("")) {
                regFirstName.setText("FirstName");

                regFirstName.setForeground(new Color(153, 153, 153));
            } else {
                regFirstName.setForeground(new Color(0, 0, 0));
            }


        }//GEN-LAST:event_regFirstNameFocusLost

        private void regLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusGained
            // TODO add your handling code here:
            if (regLastName.getText().equals("Age")) {
                regLastName.setText("");
                regLastName.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_regLastNameFocusGained

        private void regLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusLost
            // TODO add your handling code here:
            if (regLastName.getText().equals("")) {
                regLastName.setText("Age");
                regLastName.setForeground(new Color(153, 153, 153));
            } else {
                regLastName.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_regLastNameFocusLost

        private void WeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WeightFocusGained
            // TODO add your handling code here:
            if (Weight.getText().equals("Department")) {
                Weight.setText("");
                Weight.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_WeightFocusGained

        private void WeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WeightFocusLost
            // TODO add your handling code here:
            if (Weight.getText().equals("")) {
                Weight.setText("Department");
                Weight.setForeground(new Color(153, 153, 153));
            } else {
                Weight.setForeground(new Color(0, 0, 0));
            }

        }//GEN-LAST:event_WeightFocusLost

        private void regFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFirstNameActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_regFirstNameActionPerformed

        private void employmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employmentIdActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_employmentIdActionPerformed

        private void employmentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employmentIdFocusGained
            // TODO add your handling code here:
            if (employmentId.getText().equals("LRN")) {
                employmentId.setText("");
                employmentId.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_employmentIdFocusGained

        private void employmentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employmentIdFocusLost
            // TODO add your handling code here:
            if (employmentId.getText().equals("")) {
                employmentId.setText("LRN");
                employmentId.setForeground(new Color(153, 153, 153));
            } else {
                employmentId.setForeground(new Color(0, 0, 0));
            }
        }//GEN-LAST:event_employmentIdFocusLost

        private void SexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SexFocusLost
                // TODO add your handling code here:
                if (Sex.getText().equals("")) {
                        Sex.setText("Sex");
                        Sex.setForeground(new Color(153, 153, 153));
                } else {
                        Sex.setForeground(new Color(0, 0, 0));
                }
        }//GEN-LAST:event_SexFocusLost

        private void SexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SexFocusGained
                // TODO add your handling code here:
                if (Sex.getText().equals("Sex")) {
                        Sex.setText("");
                        Sex.setForeground(new Color(0, 0, 0));
                }
        }//GEN-LAST:event_SexFocusGained

        private void AgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusGained
                // TODO add your handling code here:
        }//GEN-LAST:event_AgeFocusGained

        private void AgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusLost
                // TODO add your handling code here:
        }//GEN-LAST:event_AgeFocusLost

        private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_AgeActionPerformed

        private void HeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HeightFocusGained
                // TODO add your handling code here:
        }//GEN-LAST:event_HeightFocusGained

        private void HeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HeightFocusLost
                // TODO add your handling code here:
        }//GEN-LAST:event_HeightFocusLost

        private void HeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_HeightActionPerformed

        private void Height1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Height1FocusGained
                // TODO add your handling code here:
        }//GEN-LAST:event_Height1FocusGained

        private void Height1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Height1FocusLost
                // TODO add your handling code here:
        }//GEN-LAST:event_Height1FocusLost

        private void Height1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_Height1ActionPerformed

        private void Height2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Height2FocusGained
                // TODO add your handling code here:
        }//GEN-LAST:event_Height2FocusGained

        private void Height2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Height2FocusLost
                // TODO add your handling code here:
        }//GEN-LAST:event_Height2FocusLost

        private void Height2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height2ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_Height2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationStudent().setVisible(true));
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField Age;
        private javax.swing.JTextField Height;
        private javax.swing.JTextField Height1;
        private javax.swing.JTextField Height2;
        private javax.swing.JTextField Sex;
        private javax.swing.JTextField Weight;
        private javax.swing.JTextField employmentId;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JLabel pictureBg;
        private javax.swing.JTextField regFirstName;
        private javax.swing.JTextField regLastName;
        private javax.swing.JButton register;
        // End of variables declaration//GEN-END:variables
}
