/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class RegistrationStudent extends javax.swing.JFrame {

	Connection con;
	PreparedStatement pst;
	ResultSet rs;

	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationStudent.class.getName());

	/**
	 * Creates new form RegistrationAdmin
	 */
	public RegistrationStudent() {
		initComponents();
		Connect();
		jPanel2.setBackground(new Color(38, 26, 114, 200));
	}

	/**
	 * Refresh StudentData window if it's currently open
	 */
	private void refreshStudentDataIfOpen() {
		try {
			// Find all open windows
			java.awt.Window[] windows = java.awt.Window.getWindows();
			for (java.awt.Window window : windows) {
				if (window instanceof StudentData && window.isVisible()) {
					((StudentData) window).refreshTable();
					System.out.println("✓ StudentData table refreshed");
				}
			}
		} catch (Exception e) {
			System.err.println("Could not refresh StudentData: " + e.getMessage());
		}
	}

	public final void Connect() {
		try {
			con = DatabaseConnector.getStudentConnection();
		} catch (SQLException ex) {
			System.getLogger(RegistrationStudent.class.getName()).log(System.Logger.Level.ERROR,
				(String) null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                LRN = new javax.swing.JTextField();
                Weight = new javax.swing.JTextField();
                regLastName = new javax.swing.JTextField();
                Sex = new javax.swing.JTextField();
                regFirstName = new javax.swing.JTextField();
                register = new javax.swing.JButton();
                Age = new javax.swing.JTextField();
                Section = new javax.swing.JTextField();
                Height = new javax.swing.JTextField();
                Grade = new javax.swing.JTextField();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                pictureBg = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("");
                setResizable(false);

                jPanel1.setForeground(new java.awt.Color(102, 102, 102));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel2.setBackground(new java.awt.Color(38, 26, 114));
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Registration");
                jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

                LRN.setForeground(new java.awt.Color(153, 153, 153));
                LRN.setText("LRN");
                LRN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                LRN.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                LRNFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                LRNFocusLost(evt);
                        }
                });
                LRN.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LRNActionPerformed(evt);
                        }
                });
                jPanel2.add(LRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, 40));

                Weight.setForeground(new java.awt.Color(153, 153, 153));
                Weight.setText("Weight (Kg)");
                Weight.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                Weight.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                WeightFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                WeightFocusLost(evt);
                        }
                });
                Weight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                WeightActionPerformed(evt);
                        }
                });
                jPanel2.add(Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 80, 40));

                regLastName.setForeground(new java.awt.Color(153, 153, 153));
                regLastName.setText("LastName");
                regLastName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                regLastName.setMinimumSize(new java.awt.Dimension(80, 22));
                regLastName.setPreferredSize(new java.awt.Dimension(80, 22));
                regLastName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regLastNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regLastNameFocusLost(evt);
                        }
                });
                regLastName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regLastNameActionPerformed(evt);
                        }
                });
                jPanel2.add(regLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 80, 40));

                Sex.setForeground(new java.awt.Color(153, 153, 153));
                Sex.setText("Sex");
                Sex.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                Sex.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                SexFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                SexFocusLost(evt);
                        }
                });
                jPanel2.add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 80, 40));

                regFirstName.setForeground(new java.awt.Color(153, 153, 153));
                regFirstName.setText("FirstName");
                regFirstName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                regFirstName.setMinimumSize(new java.awt.Dimension(80, 22));
                regFirstName.setPreferredSize(new java.awt.Dimension(80, 22));
                regFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regFirstNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regFirstNameFocusLost(evt);
                        }
                });
                regFirstName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regFirstNameActionPerformed(evt);
                        }
                });
                jPanel2.add(regFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 40));

                register.setForeground(new java.awt.Color(38, 26, 114));
                register.setText("Register");
                register.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                registerActionPerformed(evt);
                        }
                });
                jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

                Age.setForeground(new java.awt.Color(153, 153, 153));
                Age.setText("Age");
                Age.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                Age.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                AgeFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                AgeFocusLost(evt);
                        }
                });
                Age.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AgeActionPerformed(evt);
                        }
                });
                jPanel2.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 80, 40));

                Section.setForeground(new java.awt.Color(153, 153, 153));
                Section.setText("Section");
                Section.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                Section.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                SectionFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                SectionFocusLost(evt);
                        }
                });
                Section.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SectionActionPerformed(evt);
                        }
                });
                jPanel2.add(Section, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 170, 40));

                Height.setForeground(new java.awt.Color(153, 153, 153));
                Height.setText("Height (Cm)");
                Height.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                Height.addAncestorListener(new javax.swing.event.AncestorListener() {
                        public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                                HeightAncestorAdded(evt);
                        }
                        public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                        }
                        public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                        }
                });
                Height.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                HeightFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                HeightFocusLost(evt);
                        }
                });
                Height.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HeightActionPerformed(evt);
                        }
                });
                jPanel2.add(Height, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 80, 40));

                Grade.setForeground(new java.awt.Color(153, 153, 153));
                Grade.setText("Grade");
                Grade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                Grade.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                GradeFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                GradeFocusLost(evt);
                        }
                });
                Grade.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GradeActionPerformed(evt);
                        }
                });
                jPanel2.add(Grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 170, 40));

                jPanel3.setBackground(new java.awt.Color(38, 26, 114));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/logo_school-removebg-preview.png"))); // NOI18N

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(8, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addContainerGap(379, Short.MAX_VALUE))
                );

                jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 100, 480));

                jLabel3.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Student's");
                jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 50));

                jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 340, 490));

                pictureBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/6226336049911680989.jpg"))); // NOI18N
                jPanel1.add(pictureBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 480));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, Short.MAX_VALUE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void regLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLastNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_regLastNameActionPerformed

        private void WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_WeightActionPerformed

        private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
		// TODO add your handling code here:
		// --- 1. GATHER DATA ---
		// Ensure you use .trim() on ALL fields to remove accidental spaces
		String lrn = LRN.getText().trim();
		String firstName = regFirstName.getText().trim();
		String lastName = regLastName.getText().trim();
		String sex = Sex.getText().trim();
		String weight = Weight.getText().trim();
		String height = Height.getText().trim();
		String grade = Grade.getText().trim();
		String section = Section.getText().trim();

		// The Age field is present in your GUI component code, but missing from your data gathering here.
		// Ensure you include it if it's required by the 'student' table:
		// String age = Age.getText().trim(); // <-- Add this if needed
		// --- 2. VALIDATION ---
		if (firstName.isEmpty() || lastName.isEmpty() || sex.isEmpty() || weight.isEmpty() || height.isEmpty() || grade.isEmpty() || section.isEmpty() || lrn.isEmpty()
			|| firstName.equals("FirstName") || lastName.equals("LastName") || sex.equals("Sex") || weight.equals("Weight (Kg)") || height.equals("Height (Cm)")
			|| grade.equals("Grade") || section.equals("Section")) {
			JOptionPane.showMessageDialog(this, "Please fill all required information.", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		} else if (lrn.length() != 12) {
			JOptionPane.showMessageDialog(this, "The LRN must be exactly 12 digits.", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}

		// --- 3. DATABASE OPERATIONS SETUP ---
		Connection tempCon = con; // Use the existing connection
		PreparedStatement studentPst = null;
		PreparedStatement diagnosticPst = null;

		// Flag to manage the transaction state
		boolean transactionStarted = false;

		try {
			if (tempCon == null || tempCon.isClosed()) {
				JOptionPane.showMessageDialog(this, "Database connection not established.", "Error", JOptionPane.ERROR_MESSAGE);
				return;
			}

			// --- Start Transaction ---
			tempCon.setAutoCommit(false);
			transactionStarted = true;

			// --- A. Check for Duplicates (Checking LRN is better than name) ---
			// I will keep your name check logic for now, but LRN is the unique identifier.
			String checkQuery = "SELECT COUNT(*) FROM student WHERE LRN = ?";
			int count = 0;
			try (PreparedStatement checkSt = tempCon.prepareStatement(checkQuery)) {
				checkSt.setString(1, lrn);
				try (ResultSet rs = checkSt.executeQuery()) {
					if (rs.next()) {
						count = rs.getInt(1);
					}
				}
			}

			if (count > 0) {
				JOptionPane.showMessageDialog(null, "LRN already exists in the database!", "Error", JOptionPane.ERROR_MESSAGE);
				return;
			}

			// --- B. INSERT into student table ---
			String sqlStudent = "INSERT INTO student(LRN, FirstName, LastName, Sex, Weight, Height, Grade, Section) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
			studentPst = tempCon.prepareStatement(sqlStudent);
			studentPst.setString(1, lrn);
			studentPst.setString(2, firstName);
			studentPst.setString(3, lastName);
			studentPst.setString(4, sex);
			studentPst.setString(5, weight);
			studentPst.setString(6, height);
			studentPst.setString(7, grade);
			studentPst.setString(8, section);

			int studentResult = studentPst.executeUpdate();

			// --- C. INSERT into diagnostics table ---
			if (studentResult > 0) {
				String newFullName = firstName + " " + lastName;
				String sqlDiagnostic = "INSERT INTO diagnostics (student_lrn_fk, student_name, diagnostic_notes) VALUES (?, ?, ?)";
				diagnosticPst = tempCon.prepareStatement(sqlDiagnostic);

				diagnosticPst.setString(1, lrn); // Link using the LRN
				diagnosticPst.setString(2, newFullName);
				// This calls the method from the other class, which is good practice!
				String initialNotes = "Student registered on " + new java.util.Date().toString() + ". Awaiting clinic visit.";
				diagnosticPst.setString(3, initialNotes);

				int diagnosticResult = diagnosticPst.executeUpdate();

				// --- D. COMMIT TRANSACTION ---
				if (diagnosticResult > 0) {
					tempCon.commit(); // Save both changes permanently
					JOptionPane.showMessageDialog(this, "Registration successful ");

					// Clear fields
					LRN.setText("");
					regFirstName.setText("");
					regLastName.setText("");
					Sex.setText("");
					Weight.setText("");
					Height.setText("");
					Grade.setText("");
					Section.setText("");

					// Refresh StudentData if it's open
					refreshStudentDataIfOpen();

					this.dispose();
					// 🚨 OPTIONAL: If the nurse consultation frame is open, you should refresh it.
					// This requires a way to access the active instance of NurseConsultationFrame.
					// e.g., NurseConsultationFrame.getInstance().refreshDiagnosticsTable();

				} else {
					tempCon.rollback();
					JOptionPane.showMessageDialog(this, "Registration failed: Diagnostics record could not be created. Changes reverted.", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}

		} catch (SQLException ex) {
			// --- E. ERROR HANDLING & ROLLBACK ---
			try {
				if (transactionStarted && tempCon != null) {
					tempCon.rollback(); // Rollback any changes
				}
			} catch (SQLException rollbackEx) {
				logger.log(Level.SEVERE, "Rollback failed", rollbackEx);
			}
			logger.log(Level.SEVERE, "Registration SQL Error", ex);
			JOptionPane.showMessageDialog(this, "A database error occurred during registration: " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);

		} finally {
			// --- F. ENSURE RESOURCES ARE CLOSED AND STATE IS RESET ---
			try {
				if (studentPst != null) {
					studentPst.close();
				}
				if (diagnosticPst != null) {
					diagnosticPst.close();
				}
				if (tempCon != null && transactionStarted) {
					tempCon.setAutoCommit(true); // Reset autocommit
				}
			} catch (SQLException closeEx) {
				logger.log(Level.SEVERE, "Resource close error", closeEx);
			}
		}

        }//GEN-LAST:event_registerActionPerformed

        private void regFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusGained
		// TODO add your handling code here:
		if (regFirstName.getText().equals("FirstName")) {
			regFirstName.setText("");
			regFirstName.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_regFirstNameFocusGained

        private void regFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusLost
		// TODO add your handling code here:

		if (regFirstName.getText().equals("")) {
			regFirstName.setText("FirstName");

			regFirstName.setForeground(new Color(153, 153, 153));
		} else {
			regFirstName.setForeground(new Color(0, 0, 0));
		}


        }//GEN-LAST:event_regFirstNameFocusLost

        private void regLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusGained
		// TODO add your handling code here:
		if (regLastName.getText().equals("LastName")) {
			regLastName.setText("");
			regLastName.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_regLastNameFocusGained

        private void regLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusLost
		// TODO add your handling code here:
		if (regLastName.getText().equals("")) {
			regLastName.setText("LastName");
			regLastName.setForeground(new Color(153, 153, 153));
		} else {
			regLastName.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_regLastNameFocusLost

        private void WeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WeightFocusGained
		// TODO add your handling code here:
		if (Weight.getText().equals("Weight (Kg)")) {
			Weight.setText("");
			Weight.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_WeightFocusGained

        private void WeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WeightFocusLost
		// TODO add your handling code here:
		if (Weight.getText().equals("")) {
			Weight.setText("Weight (Kg)");
			Weight.setForeground(new Color(153, 153, 153));
		} else {
			Weight.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_WeightFocusLost

        private void regFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFirstNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_regFirstNameActionPerformed

        private void LRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LRNActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_LRNActionPerformed

        private void LRNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LRNFocusGained
		// TODO add your handling code here:
		if (LRN.getText().equals("LRN")) {
			LRN.setText("");
			LRN.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_LRNFocusGained

        private void LRNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LRNFocusLost
		// TODO add your handling code here:
		if (LRN.getText().equals("")) {
			LRN.setText("LRN");
			LRN.setForeground(new Color(153, 153, 153));
		} else {
			LRN.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_LRNFocusLost

        private void SexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SexFocusLost
		// TODO add your handling code here:
		if (Sex.getText().equals("")) {
			Sex.setText("Sex");
			Sex.setForeground(new Color(153, 153, 153));
		} else {
			Sex.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_SexFocusLost

        private void SexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SexFocusGained
		// TODO add your handling code here:
		if (Sex.getText().equals("Sex")) {
			Sex.setText("");
			Sex.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_SexFocusGained

        private void AgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusGained
		// TODO add your handling code here:
		if (Age.getText().equals("Age")) {
			Age.setText("");
			Age.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_AgeFocusGained

        private void AgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusLost
		// TODO add your handling code here:
		if (Age.getText().equals("")) {
			Age.setText("Age");
			Age.setForeground(new Color(153, 153, 153));
		} else {
			Age.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_AgeFocusLost

        private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_AgeActionPerformed

        private void SectionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SectionFocusGained
		// TODO add your handling code here:
		if (Section.getText().equals("Section")) {
			Section.setText("");
			Section.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_SectionFocusGained

        private void SectionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SectionFocusLost
		// TODO add your handling code here:
		if (Section.getText().equals("")) {
			Section.setText("Section");
			Section.setForeground(new Color(153, 153, 153));
		} else {
			Section.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_SectionFocusLost

        private void SectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_SectionActionPerformed

        private void HeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HeightFocusGained
		// TODO add your handling code here:
		if (Height.getText().equals("Height (Cm)")) {
			Height.setText("");
			Height.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_HeightFocusGained

        private void HeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HeightFocusLost
		// TODO add your handling code here:
		if (Height.getText().equals("")) {
			Height.setText("Height (Cm)");
			Height.setForeground(new Color(153, 153, 153));
		} else {
			Height.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_HeightFocusLost

        private void HeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_HeightActionPerformed

        private void GradeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GradeFocusGained
		// TODO add your handling code here:
		if (Grade.getText().equals("Grade")) {
			Grade.setText("");
			Grade.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_GradeFocusGained

        private void GradeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GradeFocusLost
		// TODO add your handling code here:if (Sex.getText().equals("Sex")) {
		if (Grade.getText().equals("")) {
			Grade.setText("Grade");
			Grade.setForeground(new Color(153, 153, 153));
		} else {
			Grade.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_GradeFocusLost

        private void GradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_GradeActionPerformed

        private void HeightAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_HeightAncestorAdded
		// TODO add your handling code here:
        }//GEN-LAST:event_HeightAncestorAdded

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new RegistrationStudent().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField Age;
        private javax.swing.JTextField Grade;
        private javax.swing.JTextField Height;
        private javax.swing.JTextField LRN;
        private javax.swing.JTextField Section;
        private javax.swing.JTextField Sex;
        private javax.swing.JTextField Weight;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JLabel pictureBg;
        private javax.swing.JTextField regFirstName;
        private javax.swing.JTextField regLastName;
        private javax.swing.JButton register;
        // End of variables declaration//GEN-END:variables
}
