/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class RegistrationAdmin extends javax.swing.JFrame {

	Connection con;
	PreparedStatement pst;
	ResultSet rs;

	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationAdmin.class.getName());

	/**
	 * Creates new form RegistrationAdmin
	 */
	public RegistrationAdmin() {
		initComponents();
		Connect();
	}

	public final void Connect() {
		try {
			Class.forName("com.mysql.jdbc.Driver");
			con = DriverManager.getConnection("jdbc:mysql://localhost/admin_data", "root", "");
		} catch (ClassNotFoundException | SQLException ex) {
			System.getLogger(RegistrationAdmin.class.getName()).log(System.Logger.Level.ERROR,
				(String) null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                employmentId = new javax.swing.JTextField();
                eyeClosedConPass = new javax.swing.JLabel();
                eyeClosedPass = new javax.swing.JLabel();
                confirmPass = new javax.swing.JPasswordField();
                regPass = new javax.swing.JPasswordField();
                department = new javax.swing.JTextField();
                regUserName = new javax.swing.JTextField();
                regFirstName = new javax.swing.JTextField();
                regLastName = new javax.swing.JTextField();
                register = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                jPanel1.setForeground(new java.awt.Color(102, 102, 102));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel2.setBackground(new java.awt.Color(38, 26, 114));
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Register");
                jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

                employmentId.setForeground(new java.awt.Color(153, 153, 153));
                employmentId.setText("Employment ID");
                employmentId.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                employmentIdFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                employmentIdFocusLost(evt);
                        }
                });
                employmentId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                employmentIdActionPerformed(evt);
                        }
                });
                jPanel2.add(employmentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 178, 40));

                eyeClosedConPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"))); // NOI18N
                jPanel2.add(eyeClosedConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

                eyeClosedPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicSystem/IMAGE/icons8-not-visible-24.png"))); // NOI18N
                eyeClosedPass.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                eyeClosedPassMousePressed(evt);
                        }
                });
                jPanel2.add(eyeClosedPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

                confirmPass.setText("Confirm Password");
                confirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                confirmPassFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                confirmPassFocusLost(evt);
                        }
                });
                jPanel2.add(confirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 178, 40));

                regPass.setText("Password");
                regPass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                regPassMouseDragged(evt);
                        }
                });
                regPass.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regPassFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regPassFocusLost(evt);
                        }
                });
                jPanel2.add(regPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 178, 40));

                department.setForeground(new java.awt.Color(153, 153, 153));
                department.setText("Department");
                department.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                departmentFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                departmentFocusLost(evt);
                        }
                });
                department.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                departmentActionPerformed(evt);
                        }
                });
                jPanel2.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 178, 40));

                regUserName.setForeground(new java.awt.Color(153, 153, 153));
                regUserName.setText("Username");
                regUserName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regUserNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regUserNameFocusLost(evt);
                        }
                });
                jPanel2.add(regUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 178, 40));

                regFirstName.setForeground(new java.awt.Color(153, 153, 153));
                regFirstName.setText("FirstName");
                regFirstName.setMinimumSize(new java.awt.Dimension(80, 22));
                regFirstName.setPreferredSize(new java.awt.Dimension(80, 22));
                regFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regFirstNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regFirstNameFocusLost(evt);
                        }
                });
                regFirstName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regFirstNameActionPerformed(evt);
                        }
                });
                jPanel2.add(regFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 40));

                regLastName.setForeground(new java.awt.Color(153, 153, 153));
                regLastName.setText("LastName");
                regLastName.setMinimumSize(new java.awt.Dimension(80, 22));
                regLastName.setPreferredSize(new java.awt.Dimension(80, 22));
                regLastName.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regLastNameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regLastNameFocusLost(evt);
                        }
                });
                regLastName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regLastNameActionPerformed(evt);
                        }
                });
                jPanel2.add(regLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 40));

                register.setForeground(new java.awt.Color(38, 26, 114));
                register.setText("Register");
                register.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                registerActionPerformed(evt);
                        }
                });
                jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

                jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 340, 470));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void regLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLastNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_regLastNameActionPerformed

        private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_departmentActionPerformed

        private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
		// TODO add your handling code here:
		String EmploymentID = employmentId.getText();
		String firstName = regFirstName.getText();
		String lastName = regLastName.getText();
		String userName = regUserName.getText();
		String depart = department.getText();
		String password = regPass.getText();
		String conPass = confirmPass.getText();

		try {
			if (firstName.isEmpty()
				|| lastName.isEmpty()
				|| userName.isEmpty()
				|| depart.isEmpty()
				|| password.isEmpty()
				|| conPass.isEmpty()
				&& firstName.equals("FirstName")
				|| lastName.equals("LastName")
				|| userName.equals("Username")
				|| depart.equals("Department")
				|| password.equals("Password")
				|| conPass.equals("Confirm Password")) {
				JOptionPane.showMessageDialog(this, "Please Fill all the needed Info", "Error", JOptionPane.ERROR_MESSAGE);
			} else {
				if (!password.equals(conPass)) {
					JOptionPane.showMessageDialog(this, "Password don't Match");

				} else {
					String checkQuery = "SELECT COUNT(*) FROM adminregistration WHERE UserName = ?";
					PreparedStatement checkSt = con.prepareStatement(checkQuery);
					checkSt.setString(1, regUserName.getText()); // Get the text from the username field
					ResultSet rs = checkSt.executeQuery();

					int count = 0;
					if (rs.next()) {
						count = rs.getInt(1);
					}

					rs.close();
					checkSt.close();

					if (count > 0) {
						// Username is already in the database
						JOptionPane.showMessageDialog(null, "Username is already taken!", "Error", JOptionPane.ERROR_MESSAGE);
					} else {

						pst = con.prepareStatement("insert into adminregistration(EmploymentId,FirstName,LastName,UserName,Department,Password,Confirm_Pass )"
							+ "values(?,?,?,?,?,?,?)");
						pst.setString(1, EmploymentID);
						pst.setString(2, firstName);
						pst.setString(3, lastName);
						pst.setString(4, userName);
						pst.setString(5, depart);
						pst.setString(6, password);
						pst.setString(7, conPass);
						int result = pst.executeUpdate();

						if (result == 1) {
							JOptionPane.showMessageDialog(this, "Registration Succesfull");
							employmentId.setText("");
							regFirstName.setText("");
							regLastName.setText("");
							regUserName.setText("");
							department.setText("");
							regPass.setText("");
							confirmPass.setText("");
							LogIn loginPage = new LogIn();
							loginPage.setVisible(true);
							this.dispose();

							pst.close();

						}
					}
				}
			}
		} catch (SQLException ex) {
			Logger.getLogger(RegistrationAdmin.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			System.getLogger(RegistrationAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
		}

        }//GEN-LAST:event_registerActionPerformed

        private void regFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusGained
		// TODO add your handling code here:
		if (regFirstName.getText().equals("FirstName")) {
			regFirstName.setText("");
			regFirstName.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_regFirstNameFocusGained

        private void regFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFirstNameFocusLost
		// TODO add your handling code here:

		if (regFirstName.getText().equals("")) {
			regFirstName.setText("FirstName");
			regFirstName.setForeground(new Color(153, 153, 153));
		} else {
			regFirstName.setForeground(new Color(0, 0, 0));
		}


        }//GEN-LAST:event_regFirstNameFocusLost

        private void regLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusGained
		// TODO add your handling code here:
		if (regLastName.getText().equals("LastName")) {
			regLastName.setText("");
			regLastName.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_regLastNameFocusGained

        private void regLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regLastNameFocusLost
		// TODO add your handling code here:
		if (regLastName.getText().equals("")) {
			regLastName.setText("LastName");
			regLastName.setForeground(new Color(153, 153, 153));
		} else {
			regLastName.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_regLastNameFocusLost

        private void regUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regUserNameFocusGained
		// TODO add your handling code here:
		if (regUserName.getText().equals("Username")) {
			regUserName.setText("");
			regUserName.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_regUserNameFocusGained

        private void regUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regUserNameFocusLost
		// TODO add your handling code here:
		if (regUserName.getText().equals("")) {
			regUserName.setText("Username");
			regUserName.setForeground(new Color(153, 153, 153));
		} else {
			regUserName.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_regUserNameFocusLost

        private void departmentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_departmentFocusGained
		// TODO add your handling code here:
		if (department.getText().equals("Department")) {
			department.setText("");
			department.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_departmentFocusGained

        private void departmentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_departmentFocusLost
		// TODO add your handling code here:
		if (department.getText().equals("")) {
			department.setText("Department");
			department.setForeground(new Color(153, 153, 153));
		} else {
			department.setForeground(new Color(0, 0, 0));
		}

        }//GEN-LAST:event_departmentFocusLost

        private void regFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFirstNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_regFirstNameActionPerformed

        private void regPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPassFocusGained
		// TODO add your handling code here:

		if (regPass.getText().equals("Password")) {
			regPass.setEchoChar('*');
			regPass.setText("");
			regPass.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_regPassFocusGained

        private void regPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPassFocusLost
		// TODO add your handling code here:

		if (regPass.getText().equals("")) {
			regPass.setEchoChar((char) 0);
			regPass.setText("Password");
			regPass.setForeground(new Color(153, 153, 153));
		} else {
			regPass.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_regPassFocusLost

        private void regPassMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regPassMouseDragged

        }//GEN-LAST:event_regPassMouseDragged

        private void confirmPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFocusGained
		// TODO add your handling code here:

		if (confirmPass.getText().equals("Confirm Password")) {
			confirmPass.setEchoChar('*');
			confirmPass.setText("");
			confirmPass.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_confirmPassFocusGained

        private void confirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFocusLost
		// TODO add your handling code here:

		if (confirmPass.getText().equals("")) {
			confirmPass.setEchoChar((char) 0);
			confirmPass.setText("Confirm Password");
			confirmPass.setForeground(new Color(153, 153, 153));
		} else {
			confirmPass.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_confirmPassFocusLost

        private void employmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employmentIdActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_employmentIdActionPerformed

        private void employmentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employmentIdFocusGained
                // TODO add your handling code here:
		if (employmentId.getText().equals("Employment ID")) {
			employmentId.setText("");
			employmentId.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_employmentIdFocusGained

        private void employmentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employmentIdFocusLost
                // TODO add your handling code here:
		if (employmentId.getText().equals("")) {
			employmentId.setText("Employment ID");
			employmentId.setForeground(new Color(153, 153, 153));
		} else {
			employmentId.setForeground(new Color(0, 0, 0));
		}
        }//GEN-LAST:event_employmentIdFocusLost

        private void eyeClosedPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeClosedPassMousePressed
                // TODO add your handling code here:
        }//GEN-LAST:event_eyeClosedPassMousePressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new RegistrationAdmin().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPasswordField confirmPass;
        private javax.swing.JTextField department;
        private javax.swing.JTextField employmentId;
        private javax.swing.JLabel eyeClosedConPass;
        private javax.swing.JLabel eyeClosedPass;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTextField regFirstName;
        private javax.swing.JTextField regLastName;
        private javax.swing.JPasswordField regPass;
        private javax.swing.JTextField regUserName;
        private javax.swing.JButton register;
        // End of variables declaration//GEN-END:variables
}
